# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FilterWidget.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FilterWidget(object):
    def setupUi(self, FilterWidget):
        FilterWidget.setObjectName("FilterWidget")
        FilterWidget.resize(323, 660)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(FilterWidget.sizePolicy().hasHeightForWidth())
        FilterWidget.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(FilterWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayoutFilterGlobal_batchSize = QtWidgets.QHBoxLayout()
        self.horizontalLayoutFilterGlobal_batchSize.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayoutFilterGlobal_batchSize.setObjectName("horizontalLayoutFilterGlobal_batchSize")
        self.labelFilterGlobal_batchSize = QtWidgets.QLabel(FilterWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelFilterGlobal_batchSize.sizePolicy().hasHeightForWidth())
        self.labelFilterGlobal_batchSize.setSizePolicy(sizePolicy)
        self.labelFilterGlobal_batchSize.setToolTip("")
        self.labelFilterGlobal_batchSize.setObjectName("labelFilterGlobal_batchSize")
        self.horizontalLayoutFilterGlobal_batchSize.addWidget(self.labelFilterGlobal_batchSize)
        self.spinBoxFilterGlobal_batchSize = QtWidgets.QSpinBox(FilterWidget)
        self.spinBoxFilterGlobal_batchSize.setMinimum(100)
        self.spinBoxFilterGlobal_batchSize.setMaximum(50000)
        self.spinBoxFilterGlobal_batchSize.setSingleStep(10)
        self.spinBoxFilterGlobal_batchSize.setObjectName("spinBoxFilterGlobal_batchSize")
        self.horizontalLayoutFilterGlobal_batchSize.addWidget(self.spinBoxFilterGlobal_batchSize)
        self.verticalLayout.addLayout(self.horizontalLayoutFilterGlobal_batchSize)
        self.groupBoxFilterSharpness = QtWidgets.QGroupBox(FilterWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxFilterSharpness.sizePolicy().hasHeightForWidth())
        self.groupBoxFilterSharpness.setSizePolicy(sizePolicy)
        self.groupBoxFilterSharpness.setCheckable(True)
        self.groupBoxFilterSharpness.setObjectName("groupBoxFilterSharpness")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBoxFilterSharpness)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayoutFilterSharpness_zscore = QtWidgets.QHBoxLayout()
        self.horizontalLayoutFilterSharpness_zscore.setObjectName("horizontalLayoutFilterSharpness_zscore")
        self.labelFilterSharpness_zscore = QtWidgets.QLabel(self.groupBoxFilterSharpness)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelFilterSharpness_zscore.sizePolicy().hasHeightForWidth())
        self.labelFilterSharpness_zscore.setSizePolicy(sizePolicy)
        self.labelFilterSharpness_zscore.setObjectName("labelFilterSharpness_zscore")
        self.horizontalLayoutFilterSharpness_zscore.addWidget(self.labelFilterSharpness_zscore)
        self.doubleSpinBoxFilterSharpness_zscore = QtWidgets.QDoubleSpinBox(self.groupBoxFilterSharpness)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBoxFilterSharpness_zscore.sizePolicy().hasHeightForWidth())
        self.doubleSpinBoxFilterSharpness_zscore.setSizePolicy(sizePolicy)
        self.doubleSpinBoxFilterSharpness_zscore.setProperty("showGroupSeparator", False)
        self.doubleSpinBoxFilterSharpness_zscore.setDecimals(2)
        self.doubleSpinBoxFilterSharpness_zscore.setMaximum(10.0)
        self.doubleSpinBoxFilterSharpness_zscore.setSingleStep(0.1)
        self.doubleSpinBoxFilterSharpness_zscore.setProperty("value", 1.0)
        self.doubleSpinBoxFilterSharpness_zscore.setObjectName("doubleSpinBoxFilterSharpness_zscore")
        self.horizontalLayoutFilterSharpness_zscore.addWidget(self.doubleSpinBoxFilterSharpness_zscore)
        self.verticalLayout_2.addLayout(self.horizontalLayoutFilterSharpness_zscore)
        self.horizontalLayoutFilterSharpness_windowSize = QtWidgets.QHBoxLayout()
        self.horizontalLayoutFilterSharpness_windowSize.setObjectName("horizontalLayoutFilterSharpness_windowSize")
        self.labelFilterSharpness_windowSize = QtWidgets.QLabel(self.groupBoxFilterSharpness)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelFilterSharpness_windowSize.sizePolicy().hasHeightForWidth())
        self.labelFilterSharpness_windowSize.setSizePolicy(sizePolicy)
        self.labelFilterSharpness_windowSize.setObjectName("labelFilterSharpness_windowSize")
        self.horizontalLayoutFilterSharpness_windowSize.addWidget(self.labelFilterSharpness_windowSize)
        self.spinBoxFilterSharpness_windowSize = QtWidgets.QSpinBox(self.groupBoxFilterSharpness)
        self.spinBoxFilterSharpness_windowSize.setMinimum(2)
        self.spinBoxFilterSharpness_windowSize.setMaximum(1000)
        self.spinBoxFilterSharpness_windowSize.setSingleStep(10)
        self.spinBoxFilterSharpness_windowSize.setProperty("value", 30)
        self.spinBoxFilterSharpness_windowSize.setObjectName("spinBoxFilterSharpness_windowSize")
        self.horizontalLayoutFilterSharpness_windowSize.addWidget(self.spinBoxFilterSharpness_windowSize)
        self.verticalLayout_2.addLayout(self.horizontalLayoutFilterSharpness_windowSize)
        self.labelFilterSharpness_status = QtWidgets.QLabel(self.groupBoxFilterSharpness)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelFilterSharpness_status.sizePolicy().hasHeightForWidth())
        self.labelFilterSharpness_status.setSizePolicy(sizePolicy)
        self.labelFilterSharpness_status.setWordWrap(True)
        self.labelFilterSharpness_status.setObjectName("labelFilterSharpness_status")
        self.verticalLayout_2.addWidget(self.labelFilterSharpness_status)
        self.pushButtonFilterSharpness_run = QtWidgets.QPushButton(self.groupBoxFilterSharpness)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonFilterSharpness_run.sizePolicy().hasHeightForWidth())
        self.pushButtonFilterSharpness_run.setSizePolicy(sizePolicy)
        self.pushButtonFilterSharpness_run.setObjectName("pushButtonFilterSharpness_run")
        self.verticalLayout_2.addWidget(self.pushButtonFilterSharpness_run)
        self.verticalLayout.addWidget(self.groupBoxFilterSharpness)
        self.groupBoxFilterCorrelation = QtWidgets.QGroupBox(FilterWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxFilterCorrelation.sizePolicy().hasHeightForWidth())
        self.groupBoxFilterCorrelation.setSizePolicy(sizePolicy)
        self.groupBoxFilterCorrelation.setCheckable(True)
        self.groupBoxFilterCorrelation.setObjectName("groupBoxFilterCorrelation")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBoxFilterCorrelation)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayoutFilterCorrelation_threshold = QtWidgets.QHBoxLayout()
        self.horizontalLayoutFilterCorrelation_threshold.setObjectName("horizontalLayoutFilterCorrelation_threshold")
        self.labelFilterCorrelation_threshold = QtWidgets.QLabel(self.groupBoxFilterCorrelation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelFilterCorrelation_threshold.sizePolicy().hasHeightForWidth())
        self.labelFilterCorrelation_threshold.setSizePolicy(sizePolicy)
        self.labelFilterCorrelation_threshold.setObjectName("labelFilterCorrelation_threshold")
        self.horizontalLayoutFilterCorrelation_threshold.addWidget(self.labelFilterCorrelation_threshold)
        self.doubleSpinBoxFilterCorrelation_threshold = QtWidgets.QDoubleSpinBox(self.groupBoxFilterCorrelation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBoxFilterCorrelation_threshold.sizePolicy().hasHeightForWidth())
        self.doubleSpinBoxFilterCorrelation_threshold.setSizePolicy(sizePolicy)
        self.doubleSpinBoxFilterCorrelation_threshold.setProperty("showGroupSeparator", False)
        self.doubleSpinBoxFilterCorrelation_threshold.setDecimals(4)
        self.doubleSpinBoxFilterCorrelation_threshold.setMaximum(1.0)
        self.doubleSpinBoxFilterCorrelation_threshold.setSingleStep(0.01)
        self.doubleSpinBoxFilterCorrelation_threshold.setProperty("value", 0.985)
        self.doubleSpinBoxFilterCorrelation_threshold.setObjectName("doubleSpinBoxFilterCorrelation_threshold")
        self.horizontalLayoutFilterCorrelation_threshold.addWidget(self.doubleSpinBoxFilterCorrelation_threshold)
        self.verticalLayout_3.addLayout(self.horizontalLayoutFilterCorrelation_threshold)
        self.labelFilterCorrelation_status = QtWidgets.QLabel(self.groupBoxFilterCorrelation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelFilterCorrelation_status.sizePolicy().hasHeightForWidth())
        self.labelFilterCorrelation_status.setSizePolicy(sizePolicy)
        self.labelFilterCorrelation_status.setObjectName("labelFilterCorrelation_status")
        self.verticalLayout_3.addWidget(self.labelFilterCorrelation_status)
        self.pushButtonFilterCorrelation_run = QtWidgets.QPushButton(self.groupBoxFilterCorrelation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonFilterCorrelation_run.sizePolicy().hasHeightForWidth())
        self.pushButtonFilterCorrelation_run.setSizePolicy(sizePolicy)
        self.pushButtonFilterCorrelation_run.setObjectName("pushButtonFilterCorrelation_run")
        self.verticalLayout_3.addWidget(self.pushButtonFilterCorrelation_run)
        self.verticalLayout.addWidget(self.groupBoxFilterCorrelation)
        self.groupBoxFilterOpticalFlow = QtWidgets.QGroupBox(FilterWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxFilterOpticalFlow.sizePolicy().hasHeightForWidth())
        self.groupBoxFilterOpticalFlow.setSizePolicy(sizePolicy)
        self.groupBoxFilterOpticalFlow.setCheckable(True)
        self.groupBoxFilterOpticalFlow.setObjectName("groupBoxFilterOpticalFlow")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBoxFilterOpticalFlow)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayoutFilterOpticalFlow_threshold = QtWidgets.QHBoxLayout()
        self.horizontalLayoutFilterOpticalFlow_threshold.setObjectName("horizontalLayoutFilterOpticalFlow_threshold")
        self.labelFilterOpticalFlow_threshold = QtWidgets.QLabel(self.groupBoxFilterOpticalFlow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelFilterOpticalFlow_threshold.sizePolicy().hasHeightForWidth())
        self.labelFilterOpticalFlow_threshold.setSizePolicy(sizePolicy)
        self.labelFilterOpticalFlow_threshold.setObjectName("labelFilterOpticalFlow_threshold")
        self.horizontalLayoutFilterOpticalFlow_threshold.addWidget(self.labelFilterOpticalFlow_threshold)
        self.doubleSpinBoxFilterOpticalFlow_threshold = QtWidgets.QDoubleSpinBox(self.groupBoxFilterOpticalFlow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBoxFilterOpticalFlow_threshold.sizePolicy().hasHeightForWidth())
        self.doubleSpinBoxFilterOpticalFlow_threshold.setSizePolicy(sizePolicy)
        self.doubleSpinBoxFilterOpticalFlow_threshold.setProperty("showGroupSeparator", False)
        self.doubleSpinBoxFilterOpticalFlow_threshold.setMaximum(1000.0)
        self.doubleSpinBoxFilterOpticalFlow_threshold.setProperty("value", 100.0)
        self.doubleSpinBoxFilterOpticalFlow_threshold.setObjectName("doubleSpinBoxFilterOpticalFlow_threshold")
        self.horizontalLayoutFilterOpticalFlow_threshold.addWidget(self.doubleSpinBoxFilterOpticalFlow_threshold)
        self.verticalLayout_4.addLayout(self.horizontalLayoutFilterOpticalFlow_threshold)
        self.horizontalLayoutFilterOpticalFlow_customParams = QtWidgets.QHBoxLayout()
        self.horizontalLayoutFilterOpticalFlow_customParams.setObjectName("horizontalLayoutFilterOpticalFlow_customParams")
        self.checkOpticalFlow_customParams = QtWidgets.QCheckBox(self.groupBoxFilterOpticalFlow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkOpticalFlow_customParams.sizePolicy().hasHeightForWidth())
        self.checkOpticalFlow_customParams.setSizePolicy(sizePolicy)
        self.checkOpticalFlow_customParams.setObjectName("checkOpticalFlow_customParams")
        self.horizontalLayoutFilterOpticalFlow_customParams.addWidget(self.checkOpticalFlow_customParams)
        self.pushButtonOpticalFlow_editParams = QtWidgets.QPushButton(self.groupBoxFilterOpticalFlow)
        self.pushButtonOpticalFlow_editParams.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonOpticalFlow_editParams.sizePolicy().hasHeightForWidth())
        self.pushButtonOpticalFlow_editParams.setSizePolicy(sizePolicy)
        self.pushButtonOpticalFlow_editParams.setObjectName("pushButtonOpticalFlow_editParams")
        self.horizontalLayoutFilterOpticalFlow_customParams.addWidget(self.pushButtonOpticalFlow_editParams)
        self.verticalLayout_4.addLayout(self.horizontalLayoutFilterOpticalFlow_customParams)
        self.labelFilterOpticalFlow_status = QtWidgets.QLabel(self.groupBoxFilterOpticalFlow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelFilterOpticalFlow_status.sizePolicy().hasHeightForWidth())
        self.labelFilterOpticalFlow_status.setSizePolicy(sizePolicy)
        self.labelFilterOpticalFlow_status.setObjectName("labelFilterOpticalFlow_status")
        self.verticalLayout_4.addWidget(self.labelFilterOpticalFlow_status)
        self.pushButtonFilterOpticalFlow_run = QtWidgets.QPushButton(self.groupBoxFilterOpticalFlow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonFilterOpticalFlow_run.sizePolicy().hasHeightForWidth())
        self.pushButtonFilterOpticalFlow_run.setSizePolicy(sizePolicy)
        self.pushButtonFilterOpticalFlow_run.setObjectName("pushButtonFilterOpticalFlow_run")
        self.verticalLayout_4.addWidget(self.pushButtonFilterOpticalFlow_run)
        self.verticalLayout.addWidget(self.groupBoxFilterOpticalFlow)
        self.pushButtonFilterGlobal_run = QtWidgets.QPushButton(FilterWidget)
        self.pushButtonFilterGlobal_run.setObjectName("pushButtonFilterGlobal_run")
        self.verticalLayout.addWidget(self.pushButtonFilterGlobal_run)

        self.retranslateUi(FilterWidget)
        self.checkOpticalFlow_customParams.toggled['bool'].connect(self.pushButtonOpticalFlow_editParams.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(FilterWidget)

    def retranslateUi(self, FilterWidget):
        _translate = QtCore.QCoreApplication.translate
        FilterWidget.setWindowTitle(_translate("FilterWidget", "GroupBox"))
        FilterWidget.setTitle(_translate("FilterWidget", "Filter"))
        self.labelFilterGlobal_batchSize.setText(_translate("FilterWidget", "Batch Size (#IMG)"))
        self.spinBoxFilterGlobal_batchSize.setToolTip(_translate("FilterWidget", "Memory dependent"))
        self.groupBoxFilterSharpness.setTitle(_translate("FilterWidget", "Sharpness"))
        self.labelFilterSharpness_zscore.setText(_translate("FilterWidget", "Z-score (single)"))
        self.labelFilterSharpness_windowSize.setText(_translate("FilterWidget", "Window Size"))
        self.spinBoxFilterSharpness_windowSize.setToolTip(_translate("FilterWidget", "Memory dependent"))
        self.labelFilterSharpness_status.setText(_translate("FilterWidget", "labelFilterSharpness_status"))
        self.pushButtonFilterSharpness_run.setText(_translate("FilterWidget", "Run"))
        self.groupBoxFilterCorrelation.setTitle(_translate("FilterWidget", "Cross Correlation"))
        self.labelFilterCorrelation_threshold.setText(_translate("FilterWidget", "Threshold"))
        self.labelFilterCorrelation_status.setText(_translate("FilterWidget", "labelFilterCorrelation_status"))
        self.pushButtonFilterCorrelation_run.setText(_translate("FilterWidget", "Run"))
        self.groupBoxFilterOpticalFlow.setTitle(_translate("FilterWidget", "Optical Flow"))
        self.labelFilterOpticalFlow_threshold.setText(_translate("FilterWidget", "Threshold"))
        self.checkOpticalFlow_customParams.setText(_translate("FilterWidget", "Custom Params"))
        self.pushButtonOpticalFlow_editParams.setText(_translate("FilterWidget", "Edit"))
        self.labelFilterOpticalFlow_status.setText(_translate("FilterWidget", "labelFilterOpticalFlow_status"))
        self.pushButtonFilterOpticalFlow_run.setText(_translate("FilterWidget", "Run"))
        self.pushButtonFilterGlobal_run.setText(_translate("FilterWidget", "Run"))

