# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VideoPlaybackControlWidget.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_VideoPlaybackControlGroupBox(object):
    def setupUi(self, VideoPlaybackControlGroupBox):
        VideoPlaybackControlGroupBox.setObjectName("VideoPlaybackControlGroupBox")
        VideoPlaybackControlGroupBox.resize(261, 232)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(VideoPlaybackControlGroupBox.sizePolicy().hasHeightForWidth())
        VideoPlaybackControlGroupBox.setSizePolicy(sizePolicy)
        self.gridLayout = QtWidgets.QGridLayout(VideoPlaybackControlGroupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalSlider_positionRatio = QtWidgets.QSlider(VideoPlaybackControlGroupBox)
        self.horizontalSlider_positionRatio.setMaximum(1000)
        self.horizontalSlider_positionRatio.setSingleStep(5)
        self.horizontalSlider_positionRatio.setPageStep(50)
        self.horizontalSlider_positionRatio.setTracking(False)
        self.horizontalSlider_positionRatio.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_positionRatio.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.horizontalSlider_positionRatio.setObjectName("horizontalSlider_positionRatio")
        self.gridLayout.addWidget(self.horizontalSlider_positionRatio, 8, 0, 1, 2)
        self.pushButton_prevFrame = QtWidgets.QPushButton(VideoPlaybackControlGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_prevFrame.sizePolicy().hasHeightForWidth())
        self.pushButton_prevFrame.setSizePolicy(sizePolicy)
        self.pushButton_prevFrame.setObjectName("pushButton_prevFrame")
        self.gridLayout.addWidget(self.pushButton_prevFrame, 3, 1, 1, 1)
        self.pushButton_nextFrame = QtWidgets.QPushButton(VideoPlaybackControlGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_nextFrame.sizePolicy().hasHeightForWidth())
        self.pushButton_nextFrame.setSizePolicy(sizePolicy)
        self.pushButton_nextFrame.setObjectName("pushButton_nextFrame")
        self.gridLayout.addWidget(self.pushButton_nextFrame, 3, 0, 1, 1)
        self.pushButton_playresume = QtWidgets.QPushButton(VideoPlaybackControlGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_playresume.sizePolicy().hasHeightForWidth())
        self.pushButton_playresume.setSizePolicy(sizePolicy)
        self.pushButton_playresume.setObjectName("pushButton_playresume")
        self.gridLayout.addWidget(self.pushButton_playresume, 1, 0, 1, 2)
        self.label_frameCount = QtWidgets.QLabel(VideoPlaybackControlGroupBox)
        self.label_frameCount.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_frameCount.setAlignment(QtCore.Qt.AlignCenter)
        self.label_frameCount.setObjectName("label_frameCount")
        self.gridLayout.addWidget(self.label_frameCount, 6, 1, 1, 1)
        self.spinBox_positionFrame = QtWidgets.QSpinBox(VideoPlaybackControlGroupBox)
        self.spinBox_positionFrame.setMinimum(1)
        self.spinBox_positionFrame.setObjectName("spinBox_positionFrame")
        self.gridLayout.addWidget(self.spinBox_positionFrame, 6, 0, 1, 1)
        self.pushButton_nextSecond = QtWidgets.QPushButton(VideoPlaybackControlGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_nextSecond.sizePolicy().hasHeightForWidth())
        self.pushButton_nextSecond.setSizePolicy(sizePolicy)
        self.pushButton_nextSecond.setObjectName("pushButton_nextSecond")
        self.gridLayout.addWidget(self.pushButton_nextSecond, 5, 0, 1, 1)
        self.pushButton_prevSecond = QtWidgets.QPushButton(VideoPlaybackControlGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_prevSecond.sizePolicy().hasHeightForWidth())
        self.pushButton_prevSecond.setSizePolicy(sizePolicy)
        self.pushButton_prevSecond.setObjectName("pushButton_prevSecond")
        self.gridLayout.addWidget(self.pushButton_prevSecond, 5, 1, 1, 1)

        self.retranslateUi(VideoPlaybackControlGroupBox)
        QtCore.QMetaObject.connectSlotsByName(VideoPlaybackControlGroupBox)

    def retranslateUi(self, VideoPlaybackControlGroupBox):
        _translate = QtCore.QCoreApplication.translate
        VideoPlaybackControlGroupBox.setWindowTitle(_translate("VideoPlaybackControlGroupBox", "GroupBox"))
        VideoPlaybackControlGroupBox.setTitle(_translate("VideoPlaybackControlGroupBox", "Video Playback Control"))
        self.pushButton_prevFrame.setText(_translate("VideoPlaybackControlGroupBox", "Prev Frame"))
        self.pushButton_nextFrame.setText(_translate("VideoPlaybackControlGroupBox", "Next Frame"))
        self.pushButton_playresume.setText(_translate("VideoPlaybackControlGroupBox", "Play/Resume"))
        self.label_frameCount.setText(_translate("VideoPlaybackControlGroupBox", "total frame"))
        self.pushButton_nextSecond.setText(_translate("VideoPlaybackControlGroupBox", "+1 sec"))
        self.pushButton_prevSecond.setText(_translate("VideoPlaybackControlGroupBox", "- 1 sec"))

